---
title: "Extension"
author: "Mike Silva"
date: "4/16/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(foreign)
library(rstanarm)
library(stargazer)
library(generics)
library(tidybayes)
library(broom)
library(modelr)

theme_set(theme_tidybayes())
``` 

```{r data}

x <- read.dta("AJPSReplication.dta") %>%
  filter(!is.na(attractive)) %>%
  mutate(
    IdeoTargetBinary = ifelse(IdeoTarget >= 4, 1, 0),
    IdeoEvalBinary = ifelse(politicalIdeo >= 4, 1, 0),
    mn_attractive_eval = mean(attractive),
    same_ideology = IdeoTargetBinary == IdeoEvalBinary,
    same_gender = Male == MaleTarget,
    ideodiffabs = abs(politicalIdeo - IdeoTarget)
  )

x <-
  x %>%
  group_by(ideval_n) %>%
  mutate(mn_attractive_eval2 = mean(attractive))
```

```{r Extension}

set.seed(02364)

stan_fit1 <-
  stan_lm(attractive ~ same_ideology + same_gender + IdeoEvalBinary + IdeoTargetBinary + Male + MaleTarget +  mn_attractive + mn_attractive_eval2, data = x, prior = NULL)

get_variables(stan_fit2)

stan_fit1 %>% 
  spread_draws(`(Intercept)`, same_ideologyTRUE)

stan1_model <-
  stan_fit1 %>%
  spread_draws(same_ideologyTRUE) %>% 
  ggplot(aes(y = .chain, x = same_ideologyTRUE)) +
  stat_halfeyeh()
 
stan_fit2 <-
  stan_lm(attractive ~ ideodiffabs + same_gender + politicalIdeo + IdeoTarget + Male + MaleTarget  + mn_attractive + mn_attractive_eval2, data = x, prior = NULL)

stan2_model <- 
  stan_fit2 %>%
  spread_draws(ideodiffabs) %>% 
  ggplot(aes(y = .chain, x = ideodiffabs)) +
  stat_halfeyeh()

stan_fit3 <- 
  stan_lm(attractive ~ ideodiffabs + same_gender, data = x, prior = NULL)

stan3_graphic <- 
  stan_fit3 %>% 
  spread_draws(ideodiffabs) %>% 
  ggplot(aes(y = .chain, x = ideodiffabs)) +
  stat_halfeyeh()

```


checking how accurate the model is 
linpred checks the model for you and sees how accurte it is

the peaks are all the integers

tails on the left and right which doesn't make sense because there can't be a negative attractive value

overall it's a good fit
within the bounds of attractive vlues
once you leave the bounds of 1-7 it loses its validity 


