---
title: "Milestone 3"
author: "Mike Silva"
date: "2/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#these seem to be some sort of package loading 
clear
dropbox
cd "TingleyAnalysisGeneral"

#Loading the data

use AJPSReplication.dta, clear

#sets the graphic scheme. Similar to theme in R

set scheme s2mono
preserve

#removing NA's from the data set?

duplicates drop type, force

#creates a histogram with ideology target as the x value. Not sure what discrete frequency refers to. 

hist IdeoTarget, freq discrete    xlabel(1(1)7) title("Target Ideology") xtitle("Liberal : Conservative")
graph save IdeoTargetHist.gph, replace

#Another histogram with male target as the x value. This time the frequency gets something to do with the x value

hist MaleTarget, freq  xlabel(0(1)1,valuelabel)    title("Target Sex") xtitle("") 
graph save GenderTargetHist.gph, replace

#restoring and preserving the data to leave a copy on the disk

restore
preserve

#removing NA's

duplicates drop ideval, force

#another histogram with political ideology as x value

hist politicalIdeo, freq discrete    xlabel(1(1)7) title("Evaluator Ideology") xtitle("Liberal : Conservative")
graph save IdeoEvalHist.gph, replace

#histogram with the male variable as the x value and frequency getting somethig to do with the x range

hist Male , freq  xlabel(0(1)1,valuelabel)    title("Evaluator Sex") xtitle("") 
graph save GenderEvalHist.gph, replace
restore

#combines the four histograms previously made for neatness in presentation

graph combine IdeoTargetHist.gph IdeoEvalHist.gph GenderTargetHist.gph GenderEvalHist.gph


estimates clear

************
  *Models reported in paper
************
  
#creates some variables that they later evaluate in the regression models. 

  *first create some new necessary variables.
*mn_attractive is the mean attractiveness measure for the targets.
*so need to create mean attraction of the evaluators, to be called mn_eval_attractive

#this seems to be the code to create the new variable

foreach k of varlist  attractive {
  sort ideval
  by ideval: egen mn_eval_`k'=mean(`k')
}

*Model 1

#turning these ideology variables into binary variables. the bins are separated by scores of 1 though 3 and 4 through 7 on a 7 point scale.

*binary versions of IdeoTarget and politicalIdeo
recode IdeoTarget 4/7=1 1/3=0, gen(IdeoTargetBinary)
recode politicalIdeo 4/7=1 1/3=0, gen(IdeoEvalBinary)

#creating a vector or variable (can't tell) that finds if the two binary variables have the same value 

*same ideology
capture drop SameIdeology
gen SameIdeology=(IdeoTargetBinary==IdeoEvalBinary)

#does the same with gender here

*same gender
gen SameGender=(Male==MaleTarget)

#renaming the variables for presentations

label var SameIdeology "Same Ideology"
label var IdeoTargetBinary "Conservative Target"
label var IdeoEvalBinary "Conservative Eval."
label var SameGender "Same Sex"
label var Male "Male Evaluator"
label var MaleTarget "Male Target"
label var mn_attractive "Avg. Target Attract"
label var  mn_eval_attractive "Avg. Eval. Attract"

#this seems to be some code that filters variables before regressing


*Unadjusted attractiveness of target = (evaluator is conservative) + (target is conservative) + (evaluator and target are the same ideology) + (evaluator is female) + (target is female) + (evaluator and target are same sex) + (mean attractiveness of target) + (mean evaluation of evaluator)

#multiple regression model constructed

reg attractive IdeoEvalBinary  IdeoTargetBinary SameIdeology Male MaleTarget SameGender  mn_attractive mn_eval_attractive, cl(ideval)

#named the model model1

est store Model1

#not sure what this does

*t-stat on interaction is 1.69

#new package loaded

*use jacknife

# Only difference in code is vce(jacknife) which I can't explain. Something to do with estimation and clustering

reg attractive IdeoEvalBinary  IdeoTargetBinary SameIdeology Male MaleTarget SameGender  mn_attractive mn_eval_attractive, vce(jackknife)
est store Model1_JK
*t-stat on interaction is 1.65

*2
*model 2

#still don't understand exactly what all of this code does. filtering variables before the regression?

*Unadjusted attractiveness of target = (evaluator ideology) + (target ideology) + ( -|evaluator ideology - target ideology| ) + (evaluator is female) + (target is female) + (evaluator and target are same sex) + (mean attractiveness of target) + (mean evaluation of evaluator)

#generates a new variable thats the absolute value of the difference between political ideology and target ideology

gen IdeoDiffAbs=-abs(politicalIdeo-IdeoTarget) 

#replaces the new variable if the two values are equal?

replace IdeoDiffAbs=. if (politicalIdeo==.|IdeoTarget==.)

#names the variable 

label var IdeoDiffAbs "-Abs. Ideology Diff."

#creates the regression model with new variable

reg attractive politicalIdeo IdeoTarget IdeoDiffAbs  Male MaleTarget SameGender  mn_attractive mn_eval_attractive, cl(ideval)
est store Model2
**t-stat negative absolute difference is 1.48

#maybe jacknife gets the coefficient estimates in a table form

*use jacknife
reg attractive politicalIdeo IdeoTarget IdeoDiffAbs  Male MaleTarget SameGender  mn_attractive mn_eval_attractive, vce(jackknife)
est store Model2_JK
**t-stat negative absolute difference is 1.42


*3
*model 3

#filters variables once again before regressing

*Unadjusted attractiveness of target = ( -|evaluator ideology - target ideology| ) + (evaluator and target are same sex) + evaluator fixed effects + target fixed effects

#converts categorical variables into dummy variables. possibly for estimation 

xi: reg attractive   IdeoDiffAbs SameGender i.ideval i.type, cl(ideval)
est store Model3

#uses vce(jacknife) for coefficient table again

xi: reg attractive   IdeoDiffAbs SameGender i.ideval i.type, vce(jackknife)
est store Model3_JK
*t stat on the negative absolute distance is t=1.45


#puts together all three regression tables into one clean table for presentation in paper

esta Model1 Model2 Model3 using "ModelResultsMainPaper.doc", se nostar brackets label drop(_I*) order(SameIdeology IdeoDiffAbs SameGender IdeoEvalBinary  IdeoTargetBinary politicalIdeo IdeoTarget Male MaleTarget ) replace
esta Model1_JK Model2_JK Model3_JK using "ModelResultsMainPaper_JK.doc", se nostar brackets label drop(_I*) order(SameIdeology IdeoDiffAbs SameGender IdeoEvalBinary  IdeoTargetBinary politicalIdeo IdeoTarget Male MaleTarget ) replace


